###請先處理好典影的字幕
#  格式請如下
#      mores7 Freq
#11 approaches   11
#16     arrows   11
#33     called   11
#44      claws   11
#55    crosses   11
#63       deep   11


##讀取用function 檔案請放在"C:/Users/Student/Desktop/data/"
my.read.csv=function(y)
{
read.csv(paste0("C:/Users/Student/Desktop/data/",y,".CSV"))
}

##my.read.csv("請填入你要分析的檔案名")
x1=my.read.csv(paste0("moneyball"))                                            #<<<<<<<<<<<<<<<要改




##過濾出現次數10以下及排序
library(dplyr)
my.read=function(x)
{
x.filter=filter(x, Freq > 10 )
x.filter.sort = x.filter[order(x.filter$Freq) , ]
x.filter.sort
}

x1filtersort=my.read(x1)





##SQL過濾出關鍵字
library(sqldf)

x1=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'water';,row.names=TRUE")
x2=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sea';,row.names=TRUE")
x3=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'river';,row.names=TRUE")
x4=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'rock';,row.names=TRUE")
x5=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'armor';,row.names=TRUE")
x6=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'weapon';,row.names=TRUE")
x7=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'camera';,row.names=TRUE")
x8=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'blue';,row.names=TRUE")
x9=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'raven';,row.names=TRUE")
x10=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'ice';,row.names=TRUE")
x11=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'love';,row.names=TRUE")
x12=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'duke';,row.names=TRUE")
x13=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'castle';,row.names=TRUE")
x14=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'queen';,row.names=TRUE")
x15=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mountain';,row.names=TRUE")
x16=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'storm';,row.names=TRUE")
x17=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'horse';,row.names=TRUE")
x18=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'prince';,row.names=TRUE")
x19=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'princess';,row.names=TRUE")
x20=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'king';,row.names=TRUE")
x21=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'white';,row.names=TRUE")
x22=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'winter';,row.names=TRUE")
x23=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'magic';,row.names=TRUE")
x24=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sister';,row.names=TRUE")
x25=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'brother';,row.names=TRUE")
x26=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mother';,row.names=TRUE")
x27=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'father';,row.names=TRUE")
x28=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'family';,row.names=TRUE")
x29=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'snowman';,row.names=TRUE")
x30=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'kingdom';,row.names=TRUE")
x31=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'turtle';,row.names=TRUE")
x32=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'creature';,row.names=TRUE")
x33=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'city';,row.names=TRUE")
x34=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'driver';,row.names=TRUE")
x35=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'jungle';,row.names=TRUE")
x36=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'ninja';,row.names=TRUE")
x37=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'lair';,row.names=TRUE")
x38=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'monster';,row.names=TRUE")
x39=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'diner';,row.names=TRUE")
x40=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cell';,row.names=TRUE")
x41=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'office';,row.names=TRUE")
x42=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'master';,row.names=TRUE")
x43=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'music';,row.names=TRUE")
x44=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mask';,row.names=TRUE")
x45=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'ship';,row.names=TRUE")
x46=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'train';,row.names=TRUE")
x47=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'space';,row.names=TRUE")
x48=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'fire';,row.names=TRUE")
x49=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'planet';,row.names=TRUE")
x50=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'metal';,row.names=TRUE")
x51=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'robot';,row.names=TRUE")
x52=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'penguin';,row.names=TRUE")
x53=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'fish';,row.names=TRUE")
x54=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'colony';,row.names=TRUE")
x55=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'evil';,row.names=TRUE")
x56=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'lab';,row.names=TRUE")
x57=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'caner';,row.names=TRUE")
x58=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cigarette';,row.names=TRUE")
x59=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'resistance';,row.names=TRUE")
x60=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'airplane';,row.names=TRUE")
x61=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'spaceship';,row.names=TRUE")
x62=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'desert';,row.names=TRUE")
x63=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'computer';,row.names=TRUE")
x64=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'dorm';,row.names=TRUE")
x65=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'friend';,row.names=TRUE")
x66=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'party';,row.names=TRUE")
x67=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'company';,row.names=TRUE")
x68=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'university';,row.names=TRUE")
x69=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'money';,row.names=TRUE")
x70=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'president';,row.names=TRUE")
x71=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'boss';,row.names=TRUE")
x72=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'colonel';,row.names=TRUE")
x73=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'military';,row.names=TRUE")
x74=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'news';,row.names=TRUE")
x75=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'conference';,row.names=TRUE")
x76=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'hotel';,row.names=TRUE")
x77=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'missal';,row.names=TRUE")
x78=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'painting';,row.names=TRUE")
x79=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'art';,row.names=TRUE")
x80=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'judge';,row.names=TRUE")
x81=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'child';,row.names=TRUE")
x82=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Asian';,row.names=TRUE")
x83=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cave';,row.names=TRUE")
x84=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'bear';,row.names=TRUE")
x85=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'strudy';,row.names=TRUE")
x86=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'helicopter';,row.names=TRUE")
x87=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'ai';,row.names=TRUE")
x88=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'beer';,row.names=TRUE")
x89=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'husband';,row.names=TRUE")
x90=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'wife';,row.names=TRUE")
x91=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'human';,row.names=TRUE")
x92=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'dragon';,row.names=TRUE")
x93=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'gun';,row.names=TRUE")
x94=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'hunter';,row.names=TRUE")
x95=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'science';,row.names=TRUE")
x96=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'warrier';,row.names=TRUE")
x97=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'village';,row.names=TRUE")
x98=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'buffalo';,row.names=TRUE")
x99=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'baseball';,row.names=TRUE")
x100=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'manager';,row.names=TRUE")
x101=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'ocean';,row.names=TRUE")
x102=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'creek';,row.names=TRUE")
x103=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'stone';,row.names=TRUE")
x104=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'shield';,row.names=TRUE")
x105=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sword';,row.names=TRUE")
x106=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cctv';,row.names=TRUE")
x107=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'snow';,row.names=TRUE")
x108=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'affection';,row.names=TRUE")
x109=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'knight';,row.names=TRUE")
x110=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'tower';,row.names=TRUE")
x111=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cliff';,row.names=TRUE")
x112=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'bllizard';,row.names=TRUE")
x113=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'pony';,row.names=TRUE")
x114=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'emperor';,row.names=TRUE")
x115=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'wizard';,row.names=TRUE")
x116=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sibling';,row.names=TRUE")
x117=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sibling';,row.names=TRUE")
x118=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mom';,row.names=TRUE")
x119=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'dad';,row.names=TRUE")
x120=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'animal';,row.names=TRUE")
x121=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'metropolis';,row.names=TRUE")
x122=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'chofer';,row.names=TRUE")
x123=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'forest';,row.names=TRUE")
x124=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'samurai';,row.names=TRUE")
x125=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'lie';,row.names=TRUE")
x126=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'beast';,row.names=TRUE")
x127=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'restaurant';,row.names=TRUE")
x128=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'slave';,row.names=TRUE")
x129=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'musical';,row.names=TRUE")
x130=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'boat';,row.names=TRUE")
x131=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'galaxy';,row.names=TRUE")
x132=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'flame';,row.names=TRUE")
x133=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'earth';,row.names=TRUE")
x134=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'iron';,row.names=TRUE")
x135=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'iron man';,row.names=TRUE")
x136=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Antarctica';,row.names=TRUE")
x137=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sea';,row.names=TRUE")
x138=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'colonial';,row.names=TRUE")
x139=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'bad';,row.names=TRUE")
x140=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'laboratory';,row.names=TRUE")
x141=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'disease';,row.names=TRUE")
x142=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'rabel';,row.names=TRUE")
x143=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'plane';,row.names=TRUE")
x144=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cockpit';,row.names=TRUE")
x145=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'internet';,row.names=TRUE")
x146=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sorority';,row.names=TRUE")
x147=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'pal';,row.names=TRUE")
x148=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'firm';,row.names=TRUE")
x149=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'college';,row.names=TRUE")
x150=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'wealth';,row.names=TRUE")
x151=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'priminister';,row.names=TRUE")
x152=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'president';,row.names=TRUE")
x153=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'military';,row.names=TRUE")
x154=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'soldier';,row.names=TRUE")
x155=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'journalist';,row.names=TRUE")
x156=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'council';,row.names=TRUE")
x157=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'hostel';,row.names=TRUE")
x158=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'rocket';,row.names=TRUE")
x159=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'canvas';,row.names=TRUE")
x160=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'artist';,row.names=TRUE")
x161=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'lawyer';,row.names=TRUE")
x162=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'children';,row.names=TRUE")
x163=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Chinese';,row.names=TRUE")
x164=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'rock';,row.names=TRUE")
x165=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'learn';,row.names=TRUE")
x166=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'chopper';,row.names=TRUE")
x167=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'artificial inteligence';,row.names=TRUE")
x168=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'wine';,row.names=TRUE")
x169=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mankind';,row.names=TRUE")
x170=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'spiner';,row.names=TRUE")
x171=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'hound';,row.names=TRUE")
x172=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'scientist';,row.names=TRUE")
x173=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'figher';,row.names=TRUE")
x174=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'town';,row.names=TRUE")
x175=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mine';,row.names=TRUE")
x176=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'visor';,row.names=TRUE")
x177=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'knife';,row.names=TRUE")
x178=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'surveillance';,row.names=TRUE")
x179=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'breeze';,row.names=TRUE")
x180=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'lord';,row.names=TRUE")
x181=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'peak';,row.names=TRUE")
x182=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'rain';,row.names=TRUE")
x183=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'donkey';,row.names=TRUE")
x184=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'voodoo';,row.names=TRUE")
x185=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mum';,row.names=TRUE")
x186=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'beast';,row.names=TRUE")
x187=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'town';,row.names=TRUE")
x188=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'pilot';,row.names=TRUE")
x189=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'woods';,row.names=TRUE")
x190=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'betray';,row.names=TRUE")
x191=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'creature';,row.names=TRUE")
x192=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'slavery';,row.names=TRUE")
x193=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'song';,row.names=TRUE")
x194=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'oiler';,row.names=TRUE")
x195=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'universe';,row.names=TRUE")
x196=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mars';,row.names=TRUE")
x197=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'steel';,row.names=TRUE")
x198=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'transformer';,row.names=TRUE")
x199=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'ocean';,row.names=TRUE")
x200=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'colonize';,row.names=TRUE")
x201=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'devil';,row.names=TRUE")
x202=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'experiment';,row.names=TRUE")
x203=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cockpit';,row.names=TRUE")
x204=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'ai';,row.names=TRUE")
x205=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'buddy';,row.names=TRUE")
x206=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'business';,row.names=TRUE")
x207=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'freshmen';,row.names=TRUE")
x208=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'gold';,row.names=TRUE")
x209=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'king';,row.names=TRUE")
x210=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'chairman';,row.names=TRUE")
x211=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'general';,row.names=TRUE")
x212=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'navy';,row.names=TRUE")
x213=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'headline';,row.names=TRUE")
x214=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'meeting';,row.names=TRUE")
x215=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'inn';,row.names=TRUE")
x216=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cannon';,row.names=TRUE")
x217=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'paint';,row.names=TRUE")
x218=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'jury';,row.names=TRUE")
x219=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'baby';,row.names=TRUE")
x220=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Japanese';,row.names=TRUE")
x221=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'stone';,row.names=TRUE")
x222=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'school';,row.names=TRUE")
x223=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == ' whiskey';,row.names=TRUE")
x224=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'homo sepiens';,row.names=TRUE")
x225=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'riffle';,row.names=TRUE")
x226=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'technology';,row.names=TRUE")
x227=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'country';,row.names=TRUE")
x228=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cliff';,row.names=TRUE")
x229=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'axe';,row.names=TRUE")
x230=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'bllizard';,row.names=TRUE")
x231=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'count';,row.names=TRUE")
x232=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'witch';,row.names=TRUE")
x233=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'black';,row.names=TRUE")
x234=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sing';,row.names=TRUE")
x235=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'tanker';,row.names=TRUE")
x236=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'moon';,row.names=TRUE")
x237=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'shark';,row.names=TRUE")
x238=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'test';,row.names=TRUE")
x239=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'web';,row.names=TRUE")
x240=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'mate';,row.names=TRUE")
x241=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'billionaire';,row.names=TRUE")
x242=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'chairman';,row.names=TRUE")
x243=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'owner';,row.names=TRUE")
x244=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'soldier';,row.names=TRUE")
x245=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'marine';,row.names=TRUE")
x246=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'report';,row.names=TRUE")
x247=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'seminar';,row.names=TRUE")
x248=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'picture';,row.names=TRUE")
x249=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'court';,row.names=TRUE")
x250=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'infant';,row.names=TRUE")
x251=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Thai';,row.names=TRUE")
x252=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'cliff';,row.names=TRUE")
x253=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'test';,row.names=TRUE")
x254=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'vodka';,row.names=TRUE")
x255=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'people';,row.names=TRUE")
x256=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'pistol';,row.names=TRUE")
x257=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'canyon';,row.names=TRUE")
x258=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'hammer';,row.names=TRUE")
x259=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'frost';,row.names=TRUE")
x260=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sir';,row.names=TRUE")
x261=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sorcerer';,row.names=TRUE")
x262=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'niggar';,row.names=TRUE")
x263=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'melody';,row.names=TRUE")
x264=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'yacht';,row.names=TRUE")
x265=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'sun';,row.names=TRUE")
x266=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'dolphine';,row.names=TRUE")
x267=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'millionaire';,row.names=TRUE")
x268=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'master';,row.names=TRUE")
x269=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'lieutenant';,row.names=TRUE")
x270=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'airforce';,row.names=TRUE")
x271=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'broadcast';,row.names=TRUE")
x272=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'potrait';,row.names=TRUE")
x273=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'todler';,row.names=TRUE")
x274=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Taiwanese';,row.names=TRUE")
x275=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'canyon';,row.names=TRUE")
x276=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'exam';,row.names=TRUE")
x277=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'gin';,row.names=TRUE")
x278=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'revolver';,row.names=TRUE")
x279=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'blade';,row.names=TRUE")
x280=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'aristocrat';,row.names=TRUE")
x281=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'private';,row.names=TRUE")
x282=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'squad';,row.names=TRUE")
x283=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'gallery';,row.names=TRUE")
x284=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'kid';,row.names=TRUE")
x285=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Cantonese';,row.names=TRUE")
x286=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'evaluation';,row.names=TRUE")
x287=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'bourbon';,row.names=TRUE")
x288=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'arrow';,row.names=TRUE")
x289=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'major';,row.names=TRUE")
x290=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'troops';,row.names=TRUE")
x291=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'drawing';,row.names=TRUE")
x292=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'Korean';,row.names=TRUE")
x293=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'brandey';,row.names=TRUE")
x294=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'bow';,row.names=TRUE")
x295=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'army';,row.names=TRUE")
x296=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'champagne';,row.names=TRUE")
x297=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'drunk';,row.names=TRUE")
x298=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'hangover';,row.names=TRUE")
x299=sqldf("SELECT * FROM x1filtersort WHERE x1filtersort.mores7 == 'tipsy';,row.names=TRUE")
domatrix=do.call(rbind, lapply( paste0("x", 1:299) , get) )



gogo=function(namess)
{
domatrix2 <- data.frame(movie=namess,keyword=domatrix$mores7,Freq=domatrix$Freq)
write.csv(domatrix2,paste0("C:/Users/Student/Desktop/",namess,".CSV") , row.names = FALSE)   
}


gogo("moneyball")                                                               #<<<<<<<<<<<<<<<要改
